### ISSUE TITLE
cannot load weights.mat

### ISSUE THREAD

**Issue by luochenhuan** [jeknov/Gender_Recognition_NN-PCA#1]
Hi!

First thank you for your share of the codes. But when I run the main.m, it seems that you didn't upload the weights.mat for the project. Could you plz add the mat file if possible?

Thank you !

**Comment by jeknov** [comment]
Hi,

mat file is a dataset. As far as I remember, that was the cropped version
of Labeled Faces in the Wild (LFW) dataset, I took it from here
http://itee.uq.edu.au/~conrad/lfwcrop/ . Or otherwise you can use any other
dataset of faces you like.
Hope, it helps.

Regards,
Jekaterina

**Comment by hamzaiefr** [comment]
Thanks for code but there's an issue in this code I think you didn't upload the load('weight.mat') file 

So can you please Attach this in the code?

%% ================ Part 2: Loading Pameters ================

load('weights.mat');
